<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="test\**" />
    <Compile Remove="GaugeControlLib\**" />
    <Page Remove="test\**" />
    <Page Remove="GaugeControlLib\**" />
    <None Remove="GaugeControlLib\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="GaugeControlLib\GaugeControlLib.csproj" />
    <ProjectReference Include="..\Shared\WpfMvvmKit\WpfMvvmKit.csproj" />
  </ItemGroup>

</Project>
