<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="test\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OxyPlot.Wpf" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\WpfMvvmKit\WpfMvvmKit.csproj" />
  </ItemGroup>

</Project>
